# Generated by Django 5.1.7 on 2025-03-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KLine',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'KLine',
            },
        ),
    ]
