# Generated by Django 5.1.7 on 2025-03-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='subtitle',
            field=models.CharField(default='', max_length=255, verbose_name='サブタイトル'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='タイトル'),
        ),
    ]
