# Generated by Django 5.1.7 on 2025-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_subtitle_alter_diary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='subtitle',
            field=models.CharField(max_length=255, null=True, verbose_name='サブタイトル'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(max_length=40, verbose_name='タイトル'),
        ),
    ]
