# Generated by Django 5.1.7 on 2025-03-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_subtitle_alter_diary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='image',
            field=models.CharField(null=True, verbose_name='image'),
        ),
    ]
