# Generated by Django 5.1.7 on 2025-03-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='image',
        ),
        migrations.AddField(
            model_name='diary',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='画像パス'),
        ),
    ]
