# Generated by Django 5.1.7 on 2025-03-29 08:34

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_remove_diary_image_diary_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=mdeditor.fields.MDTextField(default=''),
            preserve_default=False,
        ),
    ]
